### ISSUE TITLE
How to request foreign websites? CSP Error

### ISSUE THREAD

**Issue by ston2** [saucesteals/electron-typescript-react-tailwind-redux#15]
Thanks for the boilerplate!

I try to integrate external content (e.g. a font from Google Fonts) and send requests to different external websites. Nevertheless, I always get a similar error:
> Refused to load the stylesheet 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700&display=swap' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' data:". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Tried following in index.html:
> ... meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src   'self' https://fonts.googleapis.com; font-src    'self' data: https://fonts.gstatic.com; img-src     'self' data: content:; media-src   *;" />

How can I work around this CSP Error? Have already tried some things in the index.html, however, nothing was of success.

I'm glad for any help :)

**Comment by franz-geiser** [comment]
Solved in this way:
in main.ts
`const createWindow = (): void => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": ["*"],
      },
    });
  });`
  In this way the CSP is disabled.
  I will come back to this when i have a working CSP policy.
  For now it solves my issue.

**Comment by fourwadu** [comment]
This is insecure and defeats the purpose of having a CSP. 

Please do not use this in a production build. This is only acceptable for developer builds and testing.

**Comment by saucesteals** [comment]
@franz-geiser I suggest you just take a minute and write out the APIs that you're using into the csp
this is what I usually use:
```ts
const patchCSP = () => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [
          [
            "default-src 'self' 'unsafe-inline' http: https: data:",
            "script-src 'self' 'unsafe-eval' 'unsafe-inline' data:",
            "media-src 'self' file:",
          ].join("; "),
        ],
      },
    });
  });
};
```

to which you can simply add your API calls as needed

**Comment by franz-geiser** [comment]
perfect, i take it :-)
Thank you.
