### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by franz-geiser** [saucesteals/electron-typescript-react-tailwind-redux#20]
I'm trying to interact with some API, but i get a CSP error.

index.tsx?0839:15 Refused to connect to 'https://demo/api/auth/login' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' data:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

Here the code to reproduce the issue:
`const increment = async () => {
    store.dispatch(incrementChar());
    store.dispatch(incrementCounter(1));
    await fetch('https://demo/api/auth/login').then(res => {console.log(res)}).then(data => {console.log(data)})
  };
`

After some hours of trying i still can't do a single API request.
I tried to add a meta http-equiv="Content-Security-Policy" in the index.html file but it doesn't work.
I also tried to:
 - launch the command from inside the electronBridge
 - launch the command with ipcMain

Now i'm really out of ideas.

**Comment by fourwadu** [comment]
See #15

**Comment by franz-geiser** [comment]
Yep, i just saw the other issue.
Sorry.
